export enum WindowStatesEnum {
  FINDER_OPENED = "FINDER_OPENED",
  FINDER_CLOSED = "FINDER_CLOSED",
  FINDER_SIZED = "FINDER_SIZED",
  VIDEO_OPENED = "VIDEO_OPENED",
  VIDEO_CLOSED = "VIDEO_CLOSED",
  VIDEO_SIZED = "VIDEO_SIZED"
}
